ENV = {
	'BASEDIR': 'PATH_TO_D4JCLONE_BASEDIR',
	'SCRIPTDIR': 'PATH_TO_D4JCLONE_SCRIPTS',
	'REPODIR': 'PATH_TO_D4JCLONE_PROJECT_REPOSITORIES',
	'PROJECTDIR': 'PATH_TO_D4JCLONE_PROJECTS',
	'LIBDIR': 'PATH_TO_D4JCLONE_LIB',
	'TZ': 'America/Los_Angeles',
}